version: "3.8"

services:
  db:
    container_name: db
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: firstproject
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev

  api:
    container_name: api
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - "./api:/api"
    environment:
      DATABASE_HOST: "db"
    depends_on:
      - postgres

  web:
    container_name: web
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - "./web:/web"
    depends_on:
      - api

volumes:
  pgdata:
