---
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  api:
    name: API
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.4"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-api-${{ hashFiles('**/go.sum') }}-v3
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin

      - name: Run formatters
        run: make format-ci

      - name: Run linters
        run: make lint-ci

      - name: Build API
        run: make build

  web:
    name: Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-web-${{ hashFiles('**/package-lock.json') }}-v3
          path: |
            ~/.npm
            web/node_modules
            web/.next/cache

      - name: Install dependencies
        run: npm install

      - name: Run formatters
        run: npm run format-ci

      - name: Run linters
        run: npm run lint

      - name: Build Web
        run: npm run build
